// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGtzEvYNzIIvgLJaARezicDFKN94LVBI',
    appId: '1:1057674931083:web:a816aaa2249d722aa31d8e',
    messagingSenderId: '1057674931083',
    projectId: 'project-temples',
    authDomain: 'project-temples.firebaseapp.com',
    storageBucket: 'project-temples.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKt7AbuOZpSKFS27tEPf0PGrTRVFiQNA',
    appId: '1:1057674931083:android:b67399a7966b4d3da31d8e',
    messagingSenderId: '1057674931083',
    projectId: 'project-temples',
    storageBucket: 'project-temples.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkcc64x-zmt8TtLBG-Ae11V-7nz55aZyo',
    appId: '1:1057674931083:ios:efbed739f29abcffa31d8e',
    messagingSenderId: '1057674931083',
    projectId: 'project-temples',
    storageBucket: 'project-temples.appspot.com',
    iosBundleId: 'com.temples.projectTemples',
  );
}
